export enum ModalKey {
  HELLO_WORLD = 'HELLO_WORLD',
  INVITE_INTO_GROUP = 'INVITE_INTO_GROUP',
  CROP_IMAGE = 'CROP_IMAGE',
  SELECT_PAYMENT_METHOD = 'SELECT_PAYMENT_METHOD',
  REGISTER_TOURNAMENT = 'REGISTER_TOURNAMENT',
  ADD_PARTICIPANTS = 'ADD_PARTICIPANTS',
  SHOW_ORDER_DETAIL = 'SHOW_ORDER_DETAIL',
  EDIT_MATCH = 'EDIT_MATCH',
  SHOW_PACKAGE_DETAIL = 'SHOW_PACKAGE_DETAIL',
  ADD_REFEREE = 'ADD_REFEREE',
  ADD_REFEREE_GROUP_TOURNAMENT = 'ADD_REFEREE_GROUP_TOURNAMENT',
  SELECT_SEED = 'SELECT_SEED',
}
